# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

# 사운드 파일들을 포함하는 데이터 목록
sound_files = [
    ('sounds\bgm\01-The Prelude.mp3', 'sounds/bgm'),
    ('sounds\bgm\02-Opening ~ Bombing Mission.mp3', 'sounds/bgm'),
    ('sounds\bgm\03-Bombing Mission.mp3', 'sounds/bgm'),
    ('sounds\bgm\04-Mako Reactor.mp3', 'sounds/bgm'),
    ('sounds\bgm\05-Anxious Heart.mp3', 'sounds/bgm'),
    ('sounds\bgm\06-Tifa's Theme.mp3', 'sounds/bgm'),
    ('sounds\bgm\07-Barret's Theme.mp3', 'sounds/bgm'),
    ('sounds\bgm\08-Hurry!.mp3', 'sounds/bgm'),
    ('sounds\bgm\09-Lurking in the Darkness.mp3', 'sounds/bgm'),
    ('sounds\bgm\10-Shinra Corporation.mp3', 'sounds/bgm'),
    ('sounds\bgm\11-Fighting.mp3', 'sounds/bgm'),
    ('sounds\bgm\12-Fanfare.mp3', 'sounds/bgm'),
    ('sounds\bgm\13-Flowers Blooming in the Church.mp3', 'sounds/bgm'),
    ('sounds\bgm\14-Turks' Theme.mp3', 'sounds/bgm'),
    ('sounds\bgm\15-Underneath the Rotting Pizza.mp3', 'sounds/bgm'),
    ('sounds\bgm\16-Oppressed People.mp3', 'sounds/bgm'),
    ('sounds\bgm\17-Honeybee Manor.mp3', 'sounds/bgm'),
    ('sounds\bgm\18-Who Are You.mp3', 'sounds/bgm'),
    ('sounds\bgm\19-Don of the Slums.mp3', 'sounds/bgm'),
    ('sounds\bgm\20-Infiltrating Shinra Tower.mp3', 'sounds/bgm'),
    ('sounds\bgm\21-Still More Fighting.mp3', 'sounds/bgm'),
    ('sounds\bgm\22-Red XIII's Theme.mp3', 'sounds/bgm'),
    ('sounds\bgm\23-Crazy Motorcycle Chase.mp3', 'sounds/bgm'),
    ('sounds\bgm\24-Holding My Thoughts in My Heart.mp3', 'sounds/bgm'),
    ('sounds\bgm\25-Main Theme of Final Fantasy VII.mp3', 'sounds/bgm'),
    ('sounds\bgm\26-Ahead on Our Way.mp3', 'sounds/bgm'),
    ('sounds\bgm\27-Good Night, Until Tomorrow!.mp3', 'sounds/bgm'),
    ('sounds\bgm\28-On That Day, 5 Years Ago.mp3', 'sounds/bgm'),
    ('sounds\bgm\29-Farm Boy.mp3', 'sounds/bgm'),
    ('sounds\bgm\30-Waltz de Chocobo.mp3', 'sounds/bgm'),
    ('sounds\bgm\31-Electric de Chocobo.mp3', 'sounds/bgm'),
    ('sounds\bgm\32-Cinco de Chocobo.mp3', 'sounds/bgm'),
    ('sounds\bgm\33-Chasing the Black-Caped Man.mp3', 'sounds/bgm'),
    ('sounds\bgm\34-Fortress of the Condor.mp3', 'sounds/bgm'),
    ('sounds\bgm\35-Rufus' Welcoming Ceremony.mp3', 'sounds/bgm'),
    ('sounds\bgm\36-It's Difficult to Stand on Both Feet, Isn't It.mp3', 'sounds/bgm'),
    ('sounds\bgm\37-Trail of Blood.mp3', 'sounds/bgm'),
    ('sounds\bgm\38-J-E-N-O-V-A.mp3', 'sounds/bgm'),
    ('sounds\bgm\39-Continue.mp3', 'sounds/bgm'),
    ('sounds\bgm\40-Costa del Sol.mp3', 'sounds/bgm'),
    ('sounds\bgm\41-Mark of the Traitor.mp3', 'sounds/bgm'),
    ('sounds\bgm\42-Mining Town.mp3', 'sounds/bgm'),
    ('sounds\bgm\43-Gold Saucer.mp3', 'sounds/bgm'),
    ('sounds\bgm\44-Cait Sith's Theme.mp3', 'sounds/bgm'),
    ('sounds\bgm\45-Sandy Badlands.mp3', 'sounds/bgm'),
    ('sounds\bgm\46-Cosmo Canyon.mp3', 'sounds/bgm'),
    ('sounds\bgm\47-Life Stream.mp3', 'sounds/bgm'),
    ('sounds\bgm\48-Great Warrior.mp3', 'sounds/bgm'),
    ('sounds\bgm\49-Descendant of Shinobi.mp3', 'sounds/bgm'),
    ('sounds\bgm\50-Those Chosen By the Planet.mp3', 'sounds/bgm'),
    ('sounds\bgm\51-Those Chosen By the Planet (No Intro).mp3', 'sounds/bgm'),
    ('sounds\bgm\52-The Nightmare's Beginning.mp3', 'sounds/bgm'),
    ('sounds\bgm\53-Cid's Theme.mp3', 'sounds/bgm'),
    ('sounds\bgm\54-Steal the Tiny Bronco!.mp3', 'sounds/bgm'),
    ('sounds\bgm\55-Wutai.mp3', 'sounds/bgm'),
    ('sounds\bgm\56-Stolen Materia.mp3', 'sounds/bgm'),
    ('sounds\bgm\57-Racing Chocobos ~ Place Your Bets!.mp3', 'sounds/bgm'),
    ('sounds\bgm\58-Fiddle de Chocobo.mp3', 'sounds/bgm'),
    ('sounds\bgm\59-A Great Success.mp3', 'sounds/bgm'),
    ('sounds\bgm\60-Tango of Tears.mp3', 'sounds/bgm'),
    ('sounds\bgm\61-Debut.mp3', 'sounds/bgm'),
    ('sounds\bgm\62-Interrupted by Fireworks.mp3', 'sounds/bgm'),
    ('sounds\bgm\63-Forested Temple.mp3', 'sounds/bgm'),
    ('sounds\bgm\64-You Can Hear the Cry of the Planet.mp3', 'sounds/bgm'),
    ('sounds\bgm\65-Aeris' Theme.mp3', 'sounds/bgm'),
    ('sounds\bgm\66-Buried in the Snow.mp3', 'sounds/bgm'),
    ('sounds\bgm\67-The Great Northern Cave.mp3', 'sounds/bgm'),
    ('sounds\bgm\68-Reunion.mp3', 'sounds/bgm'),
    ('sounds\bgm\69-Who Am I.mp3', 'sounds/bgm'),
    ('sounds\bgm\70-Full-Scale Attack.mp3', 'sounds/bgm'),
    ('sounds\bgm\71-Weapon Raid.mp3', 'sounds/bgm'),
    ('sounds\bgm\72-The Highwind Takes to the Skies.mp3', 'sounds/bgm'),
    ('sounds\bgm\73-A Secret Sleeping in the Deep Sea.mp3', 'sounds/bgm'),
    ('sounds\bgm\74-Parochial Town.mp3', 'sounds/bgm'),
    ('sounds\bgm\75-Off the Edge of Despair.mp3', 'sounds/bgm'),
    ('sounds\bgm\76-On the Other Side of the Mountain.mp3', 'sounds/bgm'),
    ('sounds\bgm\77-Hurry, Faster!.mp3', 'sounds/bgm'),
    ('sounds\bgm\78-Sending a Dream into the Universe.mp3', 'sounds/bgm'),
    ('sounds\bgm\79-The Countdown Begins.mp3', 'sounds/bgm'),
    ('sounds\bgm\80-If You Open Your Heart....mp3', 'sounds/bgm'),
    ('sounds\bgm\81-The Mako Cannon Fires!.mp3', 'sounds/bgm'),
    ('sounds\bgm\82-Attacking Weapon!.mp3', 'sounds/bgm'),
    ('sounds\bgm\83-Shinra Explodes.mp3', 'sounds/bgm'),
    ('sounds\bgm\84-Judgement Day.mp3', 'sounds/bgm'),
    ('sounds\bgm\85-Jenova Absolute.mp3', 'sounds/bgm'),
    ('sounds\bgm\86-The Birth of God.mp3', 'sounds/bgm'),
    ('sounds\bgm\87-One-Winged Angel.mp3', 'sounds/bgm'),
    ('sounds\bgm\88-World Crisis.mp3', 'sounds/bgm'),
    ('sounds\bgm\89-Staff Roll.mp3', 'sounds/bgm'),
    ('sounds\bgm\90-The Special Pose!.mp3', 'sounds/bgm'),
    ('sounds\sfx\000.wav', 'sounds/sfx'),
    ('sounds\sfx\001.wav', 'sounds/sfx'),
    ('sounds\sfx\002.wav', 'sounds/sfx'),
    ('sounds\sfx\003.wav', 'sounds/sfx'),
    ('sounds\sfx\004.wav', 'sounds/sfx'),
    ('sounds\sfx\005.wav', 'sounds/sfx'),
    ('sounds\sfx\006.wav', 'sounds/sfx'),
    ('sounds\sfx\007.wav', 'sounds/sfx'),
    ('sounds\sfx\008.wav', 'sounds/sfx'),
    ('sounds\sfx\009.wav', 'sounds/sfx'),
    ('sounds\sfx\010.wav', 'sounds/sfx'),
    ('sounds\sfx\011.wav', 'sounds/sfx'),
    ('sounds\sfx\012.wav', 'sounds/sfx'),
    ('sounds\sfx\013.wav', 'sounds/sfx'),
    ('sounds\sfx\014.wav', 'sounds/sfx'),
    ('sounds\sfx\015.wav', 'sounds/sfx'),
    ('sounds\sfx\016.wav', 'sounds/sfx'),
    ('sounds\sfx\017.wav', 'sounds/sfx'),
    ('sounds\sfx\018.wav', 'sounds/sfx'),
    ('sounds\sfx\019.wav', 'sounds/sfx'),
    ('sounds\sfx\020.wav', 'sounds/sfx'),
    ('sounds\sfx\021.wav', 'sounds/sfx'),
    ('sounds\sfx\022.wav', 'sounds/sfx'),
    ('sounds\sfx\023.wav', 'sounds/sfx'),
    ('sounds\sfx\024.wav', 'sounds/sfx'),
    ('sounds\sfx\025.wav', 'sounds/sfx'),
    ('sounds\sfx\026.wav', 'sounds/sfx'),
    ('sounds\sfx\027.wav', 'sounds/sfx'),
    ('sounds\sfx\028.wav', 'sounds/sfx'),
    ('sounds\sfx\029.wav', 'sounds/sfx'),
    ('sounds\sfx\030.wav', 'sounds/sfx'),
    ('sounds\sfx\031.wav', 'sounds/sfx'),
    ('sounds\sfx\032.wav', 'sounds/sfx'),
    ('sounds\sfx\033.wav', 'sounds/sfx'),
    ('sounds\sfx\034.wav', 'sounds/sfx'),
    ('sounds\sfx\035.wav', 'sounds/sfx'),
    ('sounds\sfx\036.wav', 'sounds/sfx'),
    ('sounds\sfx\037.wav', 'sounds/sfx'),
    ('sounds\sfx\038.wav', 'sounds/sfx'),
    ('sounds\sfx\039.wav', 'sounds/sfx'),
    ('sounds\sfx\040.wav', 'sounds/sfx'),
    ('sounds\sfx\041.wav', 'sounds/sfx'),
    ('sounds\sfx\042.wav', 'sounds/sfx'),
    ('sounds\sfx\043.wav', 'sounds/sfx'),
    ('sounds\sfx\044.wav', 'sounds/sfx'),
    ('sounds\sfx\045.wav', 'sounds/sfx'),
    ('sounds\sfx\046.wav', 'sounds/sfx'),
    ('sounds\sfx\047.wav', 'sounds/sfx'),
    ('sounds\sfx\048.wav', 'sounds/sfx'),
    ('sounds\sfx\049.wav', 'sounds/sfx'),
    ('sounds\sfx\050.wav', 'sounds/sfx'),
    ('sounds\sfx\051.wav', 'sounds/sfx'),
    ('sounds\sfx\052.wav', 'sounds/sfx'),
    ('sounds\sfx\053.wav', 'sounds/sfx'),
    ('sounds\sfx\054.wav', 'sounds/sfx'),
    ('sounds\sfx\055.wav', 'sounds/sfx'),
    ('sounds\sfx\056.wav', 'sounds/sfx'),
    ('sounds\sfx\057.wav', 'sounds/sfx'),
    ('sounds\sfx\058.wav', 'sounds/sfx'),
    ('sounds\sfx\059.wav', 'sounds/sfx'),
    ('sounds\sfx\060.wav', 'sounds/sfx'),
    ('sounds\sfx\061.wav', 'sounds/sfx'),
    ('sounds\sfx\062.wav', 'sounds/sfx'),
    ('sounds\sfx\063.wav', 'sounds/sfx'),
    ('sounds\sfx\064.wav', 'sounds/sfx'),
    ('sounds\sfx\065.wav', 'sounds/sfx'),
    ('sounds\sfx\066.wav', 'sounds/sfx'),
    ('sounds\sfx\067.wav', 'sounds/sfx'),
    ('sounds\sfx\068.wav', 'sounds/sfx'),
    ('sounds\sfx\069.wav', 'sounds/sfx'),
    ('sounds\sfx\070.wav', 'sounds/sfx'),
    ('sounds\sfx\071.wav', 'sounds/sfx'),
    ('sounds\sfx\072.wav', 'sounds/sfx'),
    ('sounds\sfx\073.wav', 'sounds/sfx'),
    ('sounds\sfx\074.wav', 'sounds/sfx'),
    ('sounds\sfx\075.wav', 'sounds/sfx'),
    ('sounds\sfx\076.wav', 'sounds/sfx'),
    ('sounds\sfx\077.wav', 'sounds/sfx'),
    ('sounds\sfx\078.wav', 'sounds/sfx'),
    ('sounds\sfx\079.wav', 'sounds/sfx'),
    ('sounds\sfx\080.wav', 'sounds/sfx'),
    ('sounds\sfx\081.wav', 'sounds/sfx'),
    ('sounds\sfx\082.wav', 'sounds/sfx'),
    ('sounds\sfx\083.wav', 'sounds/sfx'),
    ('sounds\sfx\084.wav', 'sounds/sfx'),
    ('sounds\sfx\085.wav', 'sounds/sfx'),
    ('sounds\sfx\086.wav', 'sounds/sfx'),
    ('sounds\sfx\087.wav', 'sounds/sfx'),
    ('sounds\sfx\088.wav', 'sounds/sfx'),
    ('sounds\sfx\089.wav', 'sounds/sfx'),
    ('sounds\sfx\090.wav', 'sounds/sfx'),
    ('sounds\sfx\091.wav', 'sounds/sfx'),
    ('sounds\sfx\092.wav', 'sounds/sfx'),
    ('sounds\sfx\093.wav', 'sounds/sfx'),
    ('sounds\sfx\094.wav', 'sounds/sfx'),
    ('sounds\sfx\095.wav', 'sounds/sfx'),
    ('sounds\sfx\096.wav', 'sounds/sfx'),
    ('sounds\sfx\097.wav', 'sounds/sfx'),
    ('sounds\sfx\098.wav', 'sounds/sfx'),
    ('sounds\sfx\099.wav', 'sounds/sfx'),
    ('sounds\sfx\100.wav', 'sounds/sfx'),
    ('sounds\sfx\101.wav', 'sounds/sfx'),
    ('sounds\sfx\102.wav', 'sounds/sfx'),
    ('sounds\sfx\103.wav', 'sounds/sfx'),
    ('sounds\sfx\104.wav', 'sounds/sfx'),
    ('sounds\sfx\105.wav', 'sounds/sfx'),
    ('sounds\sfx\106.wav', 'sounds/sfx'),
    ('sounds\sfx\107.wav', 'sounds/sfx'),
    ('sounds\sfx\108.wav', 'sounds/sfx'),
    ('sounds\sfx\109.wav', 'sounds/sfx'),
    ('sounds\sfx\110.wav', 'sounds/sfx'),
    ('sounds\sfx\111.wav', 'sounds/sfx'),
    ('sounds\sfx\112.wav', 'sounds/sfx'),
    ('sounds\sfx\113.wav', 'sounds/sfx'),
    ('sounds\sfx\114.wav', 'sounds/sfx'),
    ('sounds\sfx\115.wav', 'sounds/sfx'),
    ('sounds\sfx\116.wav', 'sounds/sfx'),
    ('sounds\sfx\117.wav', 'sounds/sfx'),
    ('sounds\sfx\118.wav', 'sounds/sfx'),
    ('sounds\sfx\119.wav', 'sounds/sfx'),
    ('sounds\sfx\120.wav', 'sounds/sfx'),
    ('sounds\sfx\121.wav', 'sounds/sfx'),
    ('sounds\sfx\122.wav', 'sounds/sfx'),
    ('sounds\sfx\123.wav', 'sounds/sfx'),
    ('sounds\sfx\124.wav', 'sounds/sfx'),
    ('sounds\sfx\125.wav', 'sounds/sfx'),
    ('sounds\sfx\126.wav', 'sounds/sfx'),
    ('sounds\sfx\127.wav', 'sounds/sfx'),
    ('sounds\sfx\128.wav', 'sounds/sfx'),
    ('sounds\sfx\129.wav', 'sounds/sfx'),
    ('sounds\sfx\130.wav', 'sounds/sfx'),
    ('sounds\sfx\131.wav', 'sounds/sfx'),
    ('sounds\sfx\132.wav', 'sounds/sfx'),
    ('sounds\sfx\133.wav', 'sounds/sfx'),
    ('sounds\sfx\134.wav', 'sounds/sfx'),
    ('sounds\sfx\135.wav', 'sounds/sfx'),
    ('sounds\sfx\136.wav', 'sounds/sfx'),
    ('sounds\sfx\137.wav', 'sounds/sfx'),
    ('sounds\sfx\138.wav', 'sounds/sfx'),
    ('sounds\sfx\139.wav', 'sounds/sfx'),
    ('sounds\sfx\140.wav', 'sounds/sfx'),
    ('sounds\sfx\141.wav', 'sounds/sfx'),
    ('sounds\sfx\142.wav', 'sounds/sfx'),
    ('sounds\sfx\143.wav', 'sounds/sfx'),
    ('sounds\sfx\144.wav', 'sounds/sfx'),
    ('sounds\sfx\145.wav', 'sounds/sfx'),
    ('sounds\sfx\146.wav', 'sounds/sfx'),
    ('sounds\sfx\147.wav', 'sounds/sfx'),
    ('sounds\sfx\148.wav', 'sounds/sfx'),
    ('sounds\sfx\149.wav', 'sounds/sfx'),
    ('sounds\sfx\150.wav', 'sounds/sfx'),
    ('sounds\sfx\151.wav', 'sounds/sfx'),
    ('sounds\sfx\152.wav', 'sounds/sfx'),
    ('sounds\sfx\153.wav', 'sounds/sfx'),
    ('sounds\sfx\154.wav', 'sounds/sfx'),
    ('sounds\sfx\155.wav', 'sounds/sfx'),
    ('sounds\sfx\156.wav', 'sounds/sfx'),
    ('sounds\sfx\157.wav', 'sounds/sfx'),
    ('sounds\sfx\158.wav', 'sounds/sfx'),
    ('sounds\sfx\159.wav', 'sounds/sfx'),
    ('sounds\sfx\160.wav', 'sounds/sfx'),
    ('sounds\sfx\161.wav', 'sounds/sfx'),
    ('sounds\sfx\162.wav', 'sounds/sfx'),
    ('sounds\sfx\163.wav', 'sounds/sfx'),
    ('sounds\sfx\164.wav', 'sounds/sfx'),
    ('sounds\sfx\165.wav', 'sounds/sfx'),
    ('sounds\sfx\166.wav', 'sounds/sfx'),
    ('sounds\sfx\167.wav', 'sounds/sfx'),
    ('sounds\sfx\168.wav', 'sounds/sfx'),
    ('sounds\sfx\169.wav', 'sounds/sfx'),
    ('sounds\sfx\170.wav', 'sounds/sfx'),
    ('sounds\sfx\171.wav', 'sounds/sfx'),
    ('sounds\sfx\172.wav', 'sounds/sfx'),
    ('sounds\sfx\173.wav', 'sounds/sfx'),
    ('sounds\sfx\174.wav', 'sounds/sfx'),
    ('sounds\sfx\175.wav', 'sounds/sfx'),
    ('sounds\sfx\176.wav', 'sounds/sfx'),
    ('sounds\sfx\177.wav', 'sounds/sfx'),
    ('sounds\sfx\178.wav', 'sounds/sfx'),
    ('sounds\sfx\179.wav', 'sounds/sfx'),
    ('sounds\sfx\180.wav', 'sounds/sfx'),
    ('sounds\sfx\181.wav', 'sounds/sfx'),
    ('sounds\sfx\182.wav', 'sounds/sfx'),
    ('sounds\sfx\183.wav', 'sounds/sfx'),
    ('sounds\sfx\184.wav', 'sounds/sfx'),
    ('sounds\sfx\185.wav', 'sounds/sfx'),
    ('sounds\sfx\186.wav', 'sounds/sfx'),
    ('sounds\sfx\187.wav', 'sounds/sfx'),
    ('sounds\sfx\188.wav', 'sounds/sfx'),
    ('sounds\sfx\189.wav', 'sounds/sfx'),
    ('sounds\sfx\190.wav', 'sounds/sfx'),
    ('sounds\sfx\191.wav', 'sounds/sfx'),
    ('sounds\sfx\192.wav', 'sounds/sfx'),
    ('sounds\sfx\193.wav', 'sounds/sfx'),
    ('sounds\sfx\194.wav', 'sounds/sfx'),
    ('sounds\sfx\195.wav', 'sounds/sfx'),
    ('sounds\sfx\196.wav', 'sounds/sfx'),
    ('sounds\sfx\197.wav', 'sounds/sfx'),
    ('sounds\sfx\198.wav', 'sounds/sfx'),
    ('sounds\sfx\199.wav', 'sounds/sfx'),
    ('sounds\sfx\200.wav', 'sounds/sfx'),
    ('sounds\sfx\201.wav', 'sounds/sfx'),
    ('sounds\sfx\202.wav', 'sounds/sfx'),
    ('sounds\sfx\203.wav', 'sounds/sfx'),
    ('sounds\sfx\204.wav', 'sounds/sfx'),
    ('sounds\sfx\205.wav', 'sounds/sfx'),
    ('sounds\sfx\206.wav', 'sounds/sfx'),
    ('sounds\sfx\207.wav', 'sounds/sfx'),
    ('sounds\sfx\208.wav', 'sounds/sfx'),
    ('sounds\sfx\209.wav', 'sounds/sfx'),
    ('sounds\sfx\210.wav', 'sounds/sfx'),
    ('sounds\sfx\211.wav', 'sounds/sfx'),
    ('sounds\sfx\212.wav', 'sounds/sfx'),
    ('sounds\sfx\213.wav', 'sounds/sfx'),
    ('sounds\sfx\214.wav', 'sounds/sfx'),
    ('sounds\sfx\215.wav', 'sounds/sfx'),
    ('sounds\sfx\216.wav', 'sounds/sfx'),
    ('sounds\sfx\217.wav', 'sounds/sfx'),
    ('sounds\sfx\218.wav', 'sounds/sfx'),
    ('sounds\sfx\219.wav', 'sounds/sfx'),
    ('sounds\sfx\220.wav', 'sounds/sfx'),
    ('sounds\sfx\221.wav', 'sounds/sfx'),
    ('sounds\sfx\222.wav', 'sounds/sfx'),
    ('sounds\sfx\223.wav', 'sounds/sfx'),
    ('sounds\sfx\224.wav', 'sounds/sfx'),
    ('sounds\sfx\225.wav', 'sounds/sfx'),
    ('sounds\sfx\226.wav', 'sounds/sfx'),
    ('sounds\sfx\227.wav', 'sounds/sfx'),
    ('sounds\sfx\228.wav', 'sounds/sfx'),
    ('sounds\sfx\229.wav', 'sounds/sfx'),
    ('sounds\sfx\230.wav', 'sounds/sfx'),
    ('sounds\sfx\231.wav', 'sounds/sfx'),
    ('sounds\sfx\232.wav', 'sounds/sfx'),
    ('sounds\sfx\233.wav', 'sounds/sfx'),
    ('sounds\sfx\234.wav', 'sounds/sfx'),
    ('sounds\sfx\235.wav', 'sounds/sfx'),
    ('sounds\sfx\236.wav', 'sounds/sfx'),
    ('sounds\sfx\237.wav', 'sounds/sfx'),
    ('sounds\sfx\238.wav', 'sounds/sfx'),
    ('sounds\sfx\239.wav', 'sounds/sfx'),
    ('sounds\sfx\240.wav', 'sounds/sfx'),
    ('sounds\sfx\241.wav', 'sounds/sfx'),
    ('sounds\sfx\242.wav', 'sounds/sfx'),
    ('sounds\sfx\243.wav', 'sounds/sfx'),
    ('sounds\sfx\244.wav', 'sounds/sfx'),
    ('sounds\sfx\245.wav', 'sounds/sfx'),
    ('sounds\sfx\246.wav', 'sounds/sfx'),
    ('sounds\sfx\247.wav', 'sounds/sfx'),
    ('sounds\sfx\248.wav', 'sounds/sfx'),
    ('sounds\sfx\249.wav', 'sounds/sfx'),
    ('sounds\sfx\250.wav', 'sounds/sfx'),
    ('sounds\sfx\251.wav', 'sounds/sfx'),
    ('sounds\sfx\252.wav', 'sounds/sfx'),
    ('sounds\sfx\253.wav', 'sounds/sfx'),
    ('sounds\sfx\254.wav', 'sounds/sfx'),
    ('sounds\sfx\255.wav', 'sounds/sfx'),
    ('sounds\sfx\256.wav', 'sounds/sfx'),
    ('sounds\sfx\257.wav', 'sounds/sfx'),
    ('sounds\sfx\258.wav', 'sounds/sfx'),
    ('sounds\sfx\259.wav', 'sounds/sfx'),
    ('sounds\sfx\260.wav', 'sounds/sfx'),
    ('sounds\sfx\261.wav', 'sounds/sfx'),
    ('sounds\sfx\262.wav', 'sounds/sfx'),
    ('sounds\sfx\263.wav', 'sounds/sfx'),
    ('sounds\sfx\264.wav', 'sounds/sfx'),
    ('sounds\sfx\265.wav', 'sounds/sfx'),
    ('sounds\sfx\266.wav', 'sounds/sfx'),
    ('sounds\sfx\267.wav', 'sounds/sfx'),
    ('sounds\sfx\268.wav', 'sounds/sfx'),
    ('sounds\sfx\269.wav', 'sounds/sfx'),
    ('sounds\sfx\270.wav', 'sounds/sfx'),
    ('sounds\sfx\271.wav', 'sounds/sfx'),
    ('sounds\sfx\272.wav', 'sounds/sfx'),
    ('sounds\sfx\273.wav', 'sounds/sfx'),
    ('sounds\sfx\274.wav', 'sounds/sfx'),
    ('sounds\sfx\275.wav', 'sounds/sfx'),
    ('sounds\sfx\276.wav', 'sounds/sfx'),
    ('sounds\sfx\277.wav', 'sounds/sfx'),
    ('sounds\sfx\278.wav', 'sounds/sfx'),
    ('sounds\sfx\279.wav', 'sounds/sfx'),
    ('sounds\sfx\280.wav', 'sounds/sfx'),
    ('sounds\sfx\281.wav', 'sounds/sfx'),
    ('sounds\sfx\282.wav', 'sounds/sfx'),
    ('sounds\sfx\283.wav', 'sounds/sfx'),
    ('sounds\sfx\284.wav', 'sounds/sfx'),
    ('sounds\sfx\285.wav', 'sounds/sfx'),
    ('sounds\sfx\286.wav', 'sounds/sfx'),
    ('sounds\sfx\287.wav', 'sounds/sfx'),
    ('sounds\sfx\288.wav', 'sounds/sfx'),
    ('sounds\sfx\289.wav', 'sounds/sfx'),
    ('sounds\sfx\290.wav', 'sounds/sfx'),
    ('sounds\sfx\291.wav', 'sounds/sfx'),
    ('sounds\sfx\292.wav', 'sounds/sfx'),
    ('sounds\sfx\293.wav', 'sounds/sfx'),
    ('sounds\sfx\294.wav', 'sounds/sfx'),
    ('sounds\sfx\295.wav', 'sounds/sfx'),
    ('sounds\sfx\296.wav', 'sounds/sfx'),
    ('sounds\sfx\297.wav', 'sounds/sfx'),
    ('sounds\sfx\298.wav', 'sounds/sfx'),
    ('sounds\sfx\299.wav', 'sounds/sfx'),
    ('sounds\sfx\300.wav', 'sounds/sfx'),
    ('sounds\sfx\301.wav', 'sounds/sfx'),
    ('sounds\sfx\302.wav', 'sounds/sfx'),
    ('sounds\sfx\303.wav', 'sounds/sfx'),
    ('sounds\sfx\304.wav', 'sounds/sfx'),
    ('sounds\sfx\305.wav', 'sounds/sfx'),
    ('sounds\sfx\306.wav', 'sounds/sfx'),
    ('sounds\sfx\307.wav', 'sounds/sfx'),
    ('sounds\sfx\308.wav', 'sounds/sfx'),
    ('sounds\sfx\309.wav', 'sounds/sfx'),
    ('sounds\sfx\310.wav', 'sounds/sfx'),
    ('sounds\sfx\311.wav', 'sounds/sfx'),
    ('sounds\sfx\312.wav', 'sounds/sfx'),
    ('sounds\sfx\313.wav', 'sounds/sfx'),
    ('sounds\sfx\314.wav', 'sounds/sfx'),
    ('sounds\sfx\315.wav', 'sounds/sfx'),
    ('sounds\sfx\316.wav', 'sounds/sfx'),
    ('sounds\sfx\317.wav', 'sounds/sfx'),
    ('sounds\sfx\318.wav', 'sounds/sfx'),
    ('sounds\sfx\319.wav', 'sounds/sfx'),
    ('sounds\sfx\320.wav', 'sounds/sfx'),
    ('sounds\sfx\321.wav', 'sounds/sfx'),
    ('sounds\sfx\322.wav', 'sounds/sfx'),
    ('sounds\sfx\323.wav', 'sounds/sfx'),
    ('sounds\sfx\324.wav', 'sounds/sfx'),
    ('sounds\sfx\325.wav', 'sounds/sfx'),
    ('sounds\sfx\326.wav', 'sounds/sfx'),
    ('sounds\sfx\327.wav', 'sounds/sfx'),
    ('sounds\sfx\328.wav', 'sounds/sfx'),
    ('sounds\sfx\329.wav', 'sounds/sfx'),
    ('sounds\sfx\330.wav', 'sounds/sfx'),
    ('sounds\sfx\331.wav', 'sounds/sfx'),
    ('sounds\sfx\332.wav', 'sounds/sfx'),
    ('sounds\sfx\333.wav', 'sounds/sfx'),
    ('sounds\sfx\334.wav', 'sounds/sfx'),
    ('sounds\sfx\335.wav', 'sounds/sfx'),
    ('sounds\sfx\336.wav', 'sounds/sfx'),
    ('sounds\sfx\337.wav', 'sounds/sfx'),
    ('sounds\sfx\338.wav', 'sounds/sfx'),
    ('sounds\sfx\339.wav', 'sounds/sfx'),
    ('sounds\sfx\340.wav', 'sounds/sfx'),
    ('sounds\sfx\341.wav', 'sounds/sfx'),
    ('sounds\sfx\342.wav', 'sounds/sfx'),
    ('sounds\sfx\343.wav', 'sounds/sfx'),
    ('sounds\sfx\344.wav', 'sounds/sfx'),
    ('sounds\sfx\345.wav', 'sounds/sfx'),
    ('sounds\sfx\346.wav', 'sounds/sfx'),
    ('sounds\sfx\347.wav', 'sounds/sfx'),
    ('sounds\sfx\348.wav', 'sounds/sfx'),
    ('sounds\sfx\349.wav', 'sounds/sfx'),
    ('sounds\sfx\350.wav', 'sounds/sfx'),
    ('sounds\sfx\351.wav', 'sounds/sfx'),
    ('sounds\sfx\352.wav', 'sounds/sfx'),
    ('sounds\sfx\353.wav', 'sounds/sfx'),
    ('sounds\sfx\354.wav', 'sounds/sfx'),
    ('sounds\sfx\355.wav', 'sounds/sfx'),
    ('sounds\sfx\356.wav', 'sounds/sfx'),
    ('sounds\sfx\357.wav', 'sounds/sfx'),
    ('sounds\sfx\358.wav', 'sounds/sfx'),
    ('sounds\sfx\359.wav', 'sounds/sfx'),
    ('sounds\sfx\360.wav', 'sounds/sfx'),
    ('sounds\sfx\361.wav', 'sounds/sfx'),
    ('sounds\sfx\362.wav', 'sounds/sfx'),
    ('sounds\sfx\363.wav', 'sounds/sfx'),
    ('sounds\sfx\364.wav', 'sounds/sfx'),
    ('sounds\sfx\365.wav', 'sounds/sfx'),
    ('sounds\sfx\366.wav', 'sounds/sfx'),
    ('sounds\sfx\367.wav', 'sounds/sfx'),
    ('sounds\sfx\368.wav', 'sounds/sfx'),
    ('sounds\sfx\369.wav', 'sounds/sfx'),
    ('sounds\sfx\370.wav', 'sounds/sfx'),
    ('sounds\sfx\371.wav', 'sounds/sfx'),
    ('sounds\sfx\372.wav', 'sounds/sfx'),
    ('sounds\sfx\373.wav', 'sounds/sfx'),
    ('sounds\sfx\374.wav', 'sounds/sfx'),
    ('sounds\sfx\375.wav', 'sounds/sfx'),
    ('sounds\sfx\376.wav', 'sounds/sfx'),
    ('sounds\sfx\377.wav', 'sounds/sfx'),
    ('sounds\sfx\378.wav', 'sounds/sfx'),
    ('sounds\sfx\379.wav', 'sounds/sfx'),
    ('sounds\sfx\380.wav', 'sounds/sfx'),
    ('sounds\sfx\381.wav', 'sounds/sfx'),
    ('sounds\sfx\382.wav', 'sounds/sfx'),
    ('sounds\sfx\383.wav', 'sounds/sfx'),
    ('sounds\sfx\384.wav', 'sounds/sfx'),
    ('sounds\sfx\385.wav', 'sounds/sfx'),
    ('sounds\sfx\386.wav', 'sounds/sfx'),
    ('sounds\sfx\387.wav', 'sounds/sfx'),
    ('sounds\sfx\388.wav', 'sounds/sfx'),
    ('sounds\sfx\389.wav', 'sounds/sfx'),
    ('sounds\sfx\390.wav', 'sounds/sfx'),
    ('sounds\sfx\391.wav', 'sounds/sfx'),
    ('sounds\sfx\392.wav', 'sounds/sfx'),
    ('sounds\sfx\393.wav', 'sounds/sfx'),
    ('sounds\sfx\394.wav', 'sounds/sfx'),
    ('sounds\sfx\395.wav', 'sounds/sfx'),
    ('sounds\sfx\396.wav', 'sounds/sfx'),
    ('sounds\sfx\397.wav', 'sounds/sfx'),
    ('sounds\sfx\398.wav', 'sounds/sfx'),
    ('sounds\sfx\399.wav', 'sounds/sfx'),
    ('sounds\sfx\400.wav', 'sounds/sfx'),
    ('sounds\sfx\401.wav', 'sounds/sfx'),
    ('sounds\sfx\402.wav', 'sounds/sfx'),
    ('sounds\sfx\403.wav', 'sounds/sfx'),
    ('sounds\sfx\404.wav', 'sounds/sfx'),
    ('sounds\sfx\405.wav', 'sounds/sfx'),
    ('sounds\sfx\406.wav', 'sounds/sfx'),
    ('sounds\sfx\407.wav', 'sounds/sfx'),
    ('sounds\sfx\408.wav', 'sounds/sfx'),
    ('sounds\sfx\409.wav', 'sounds/sfx'),
    ('sounds\sfx\410.wav', 'sounds/sfx'),
    ('sounds\sfx\411.wav', 'sounds/sfx'),
    ('sounds\sfx\412.wav', 'sounds/sfx'),
    ('sounds\sfx\413.wav', 'sounds/sfx'),
    ('sounds\sfx\414.wav', 'sounds/sfx'),
    ('sounds\sfx\415.wav', 'sounds/sfx'),
    ('sounds\sfx\416.wav', 'sounds/sfx'),
    ('sounds\sfx\417.wav', 'sounds/sfx'),
    ('sounds\sfx\418.wav', 'sounds/sfx'),
    ('sounds\sfx\419.wav', 'sounds/sfx'),
    ('sounds\sfx\420.wav', 'sounds/sfx'),
    ('sounds\sfx\421.wav', 'sounds/sfx'),
    ('sounds\sfx\422.wav', 'sounds/sfx'),
    ('sounds\sfx\423.wav', 'sounds/sfx'),
    ('sounds\sfx\424.wav', 'sounds/sfx'),
    ('sounds\sfx\425.wav', 'sounds/sfx'),
    ('sounds\sfx\426.wav', 'sounds/sfx'),
    ('sounds\sfx\427.wav', 'sounds/sfx'),
    ('sounds\sfx\428.wav', 'sounds/sfx'),
    ('sounds\sfx\429.wav', 'sounds/sfx'),
    ('sounds\sfx\430.wav', 'sounds/sfx'),
    ('sounds\sfx\431.wav', 'sounds/sfx'),
    ('sounds\sfx\432.wav', 'sounds/sfx'),
    ('sounds\sfx\433.wav', 'sounds/sfx'),
    ('sounds\sfx\434.wav', 'sounds/sfx'),
    ('sounds\sfx\435.wav', 'sounds/sfx'),
    ('sounds\sfx\436.wav', 'sounds/sfx'),
    ('sounds\sfx\437.wav', 'sounds/sfx'),
    ('sounds\sfx\438.wav', 'sounds/sfx'),
    ('sounds\sfx\439.wav', 'sounds/sfx'),
    ('sounds\sfx\440.wav', 'sounds/sfx'),
    ('sounds\sfx\441.wav', 'sounds/sfx'),
    ('sounds\sfx\442.wav', 'sounds/sfx'),
    ('sounds\sfx\443.wav', 'sounds/sfx'),
    ('sounds\sfx\444.wav', 'sounds/sfx'),
    ('sounds\sfx\445.wav', 'sounds/sfx'),
    ('sounds\sfx\446.wav', 'sounds/sfx'),
    ('sounds\sfx\447.wav', 'sounds/sfx'),
    ('sounds\sfx\448.wav', 'sounds/sfx'),
    ('sounds\sfx\449.wav', 'sounds/sfx'),
    ('sounds\sfx\450.wav', 'sounds/sfx'),
    ('sounds\sfx\451.wav', 'sounds/sfx'),
    ('sounds\sfx\452.wav', 'sounds/sfx'),
    ('sounds\sfx\453.wav', 'sounds/sfx'),
    ('sounds\sfx\454.wav', 'sounds/sfx'),
    ('sounds\sfx\455.wav', 'sounds/sfx'),
    ('sounds\sfx\456.wav', 'sounds/sfx'),
    ('sounds\sfx\457.wav', 'sounds/sfx'),
    ('sounds\sfx\458.wav', 'sounds/sfx'),
    ('sounds\sfx\459.wav', 'sounds/sfx'),
    ('sounds\sfx\460.wav', 'sounds/sfx'),
    ('sounds\sfx\461.wav', 'sounds/sfx'),
    ('sounds\sfx\462.wav', 'sounds/sfx'),
    ('sounds\sfx\463.wav', 'sounds/sfx'),
    ('sounds\sfx\464.wav', 'sounds/sfx'),
    ('sounds\sfx\465.wav', 'sounds/sfx'),
    ('sounds\sfx\466.wav', 'sounds/sfx'),
    ('sounds\sfx\467.wav', 'sounds/sfx'),
    ('sounds\sfx\468.wav', 'sounds/sfx'),
    ('sounds\sfx\469.wav', 'sounds/sfx'),
    ('sounds\sfx\470.wav', 'sounds/sfx'),
    ('sounds\sfx\471.wav', 'sounds/sfx'),
    ('sounds\sfx\472.wav', 'sounds/sfx'),
    ('sounds\sfx\473.wav', 'sounds/sfx'),
    ('sounds\sfx\474.wav', 'sounds/sfx'),
    ('sounds\sfx\475.wav', 'sounds/sfx'),
    ('sounds\sfx\476.wav', 'sounds/sfx'),
    ('sounds\sfx\477.wav', 'sounds/sfx'),
    ('sounds\sfx\478.wav', 'sounds/sfx'),
    ('sounds\sfx\479.wav', 'sounds/sfx'),
    ('sounds\sfx\480.wav', 'sounds/sfx'),
    ('sounds\sfx\481.wav', 'sounds/sfx'),
    ('sounds\sfx\482.wav', 'sounds/sfx'),
    ('sounds\sfx\483.wav', 'sounds/sfx'),
    ('sounds\sfx\484.wav', 'sounds/sfx'),
    ('sounds\sfx\485.wav', 'sounds/sfx'),
    ('sounds\sfx\486.wav', 'sounds/sfx'),
    ('sounds\sfx\487.wav', 'sounds/sfx'),
    ('sounds\sfx\488.wav', 'sounds/sfx'),
    ('sounds\sfx\489.wav', 'sounds/sfx'),
    ('sounds\sfx\490.wav', 'sounds/sfx'),
    ('sounds\sfx\491.wav', 'sounds/sfx'),
    ('sounds\sfx\492.wav', 'sounds/sfx'),
    ('sounds\sfx\493.wav', 'sounds/sfx'),
    ('sounds\sfx\494.wav', 'sounds/sfx'),
    ('sounds\sfx\495.wav', 'sounds/sfx'),
    ('sounds\sfx\496.wav', 'sounds/sfx'),
    ('sounds\sfx\497.wav', 'sounds/sfx'),
    ('sounds\sfx\498.wav', 'sounds/sfx'),
    ('sounds\sfx\499.wav', 'sounds/sfx'),
    ('sounds\sfx\500.wav', 'sounds/sfx'),
    ('sounds\sfx\501.wav', 'sounds/sfx'),
    ('sounds\sfx\502.wav', 'sounds/sfx'),
    ('sounds\sfx\503.wav', 'sounds/sfx'),
    ('sounds\sfx\504.wav', 'sounds/sfx'),
    ('sounds\sfx\505.wav', 'sounds/sfx'),
    ('sounds\sfx\506.wav', 'sounds/sfx'),
    ('sounds\sfx\507.wav', 'sounds/sfx'),
    ('sounds\sfx\508.wav', 'sounds/sfx'),
    ('sounds\sfx\509.wav', 'sounds/sfx'),
    ('sounds\sfx\510.wav', 'sounds/sfx'),
    ('sounds\sfx\511.wav', 'sounds/sfx'),
    ('sounds\sfx\512.wav', 'sounds/sfx'),
    ('sounds\sfx\513.wav', 'sounds/sfx'),
    ('sounds\sfx\514.wav', 'sounds/sfx'),
    ('sounds\sfx\515.wav', 'sounds/sfx'),
    ('sounds\sfx\516.wav', 'sounds/sfx'),
    ('sounds\sfx\517.wav', 'sounds/sfx'),
    ('sounds\sfx\518.wav', 'sounds/sfx'),
    ('sounds\sfx\519.wav', 'sounds/sfx'),
    ('sounds\sfx\520.wav', 'sounds/sfx'),
    ('sounds\sfx\521.wav', 'sounds/sfx'),
    ('sounds\sfx\522.wav', 'sounds/sfx'),
    ('sounds\sfx\523.wav', 'sounds/sfx'),
    ('sounds\sfx\524.wav', 'sounds/sfx'),
    ('sounds\sfx\525.wav', 'sounds/sfx'),
    ('sounds\sfx\526.wav', 'sounds/sfx'),
    ('sounds\sfx\527.wav', 'sounds/sfx'),
    ('sounds\sfx\528.wav', 'sounds/sfx'),
    ('sounds\sfx\529.wav', 'sounds/sfx'),
    ('sounds\sfx\530.wav', 'sounds/sfx'),
    ('sounds\sfx\531.wav', 'sounds/sfx'),
    ('sounds\sfx\532.wav', 'sounds/sfx'),
    ('sounds\sfx\533.wav', 'sounds/sfx'),
    ('sounds\sfx\534.wav', 'sounds/sfx'),
    ('sounds\sfx\535.wav', 'sounds/sfx'),
    ('sounds\sfx\536.wav', 'sounds/sfx'),
    ('sounds\sfx\537.wav', 'sounds/sfx'),
    ('sounds\sfx\538.wav', 'sounds/sfx'),
    ('sounds\sfx\539.wav', 'sounds/sfx'),
    ('sounds\sfx\540.wav', 'sounds/sfx'),
    ('sounds\sfx\541.wav', 'sounds/sfx'),
    ('sounds\sfx\542.wav', 'sounds/sfx'),
    ('sounds\sfx\543.wav', 'sounds/sfx'),
    ('sounds\sfx\544.wav', 'sounds/sfx'),
    ('sounds\sfx\545.wav', 'sounds/sfx'),
    ('sounds\sfx\546.wav', 'sounds/sfx'),
    ('sounds\sfx\547.wav', 'sounds/sfx'),
    ('sounds\sfx\548.wav', 'sounds/sfx'),
    ('sounds\sfx\549.wav', 'sounds/sfx'),
    ('sounds\sfx\550.wav', 'sounds/sfx'),
    ('sounds\sfx\551.wav', 'sounds/sfx'),
    ('sounds\sfx\552.wav', 'sounds/sfx'),
    ('sounds\sfx\553.wav', 'sounds/sfx'),
    ('sounds\sfx\554.wav', 'sounds/sfx'),
    ('sounds\sfx\555.wav', 'sounds/sfx'),
    ('sounds\sfx\556.wav', 'sounds/sfx'),
    ('sounds\sfx\557.wav', 'sounds/sfx'),
    ('sounds\sfx\558.wav', 'sounds/sfx'),
    ('sounds\sfx\559.wav', 'sounds/sfx'),
    ('sounds\sfx\560.wav', 'sounds/sfx'),
    ('sounds\sfx\561.wav', 'sounds/sfx'),
    ('sounds\sfx\562.wav', 'sounds/sfx'),
    ('sounds\sfx\563.wav', 'sounds/sfx'),
    ('sounds\sfx\564.wav', 'sounds/sfx'),
    ('sounds\sfx\565.wav', 'sounds/sfx'),
    ('sounds\sfx\566.wav', 'sounds/sfx'),
    ('sounds\sfx\567.wav', 'sounds/sfx'),
    ('sounds\sfx\568.wav', 'sounds/sfx'),
    ('sounds\sfx\569.wav', 'sounds/sfx'),
    ('sounds\sfx\570.wav', 'sounds/sfx'),
    ('sounds\sfx\571.wav', 'sounds/sfx'),
    ('sounds\sfx\572.wav', 'sounds/sfx'),
    ('sounds\sfx\573.wav', 'sounds/sfx'),
    ('sounds\sfx\574.wav', 'sounds/sfx'),
    ('sounds\sfx\575.wav', 'sounds/sfx'),
    ('sounds\sfx\576.wav', 'sounds/sfx'),
    ('sounds\sfx\577.wav', 'sounds/sfx'),
    ('sounds\sfx\578.wav', 'sounds/sfx'),
    ('sounds\sfx\579.wav', 'sounds/sfx'),
    ('sounds\sfx\580.wav', 'sounds/sfx'),
    ('sounds\sfx\581.wav', 'sounds/sfx'),
    ('sounds\sfx\582.wav', 'sounds/sfx'),
    ('sounds\sfx\583.wav', 'sounds/sfx'),
    ('sounds\sfx\584.wav', 'sounds/sfx'),
    ('sounds\sfx\585.wav', 'sounds/sfx'),
    ('sounds\sfx\586.wav', 'sounds/sfx'),
    ('sounds\sfx\587.wav', 'sounds/sfx'),
    ('sounds\sfx\588.wav', 'sounds/sfx'),
    ('sounds\sfx\589.wav', 'sounds/sfx'),
    ('sounds\sfx\590.wav', 'sounds/sfx'),
    ('sounds\sfx\591.wav', 'sounds/sfx'),
    ('sounds\sfx\592.wav', 'sounds/sfx'),
    ('sounds\sfx\593.wav', 'sounds/sfx'),
    ('sounds\sfx\594.wav', 'sounds/sfx'),
    ('sounds\sfx\595.wav', 'sounds/sfx'),
    ('sounds\sfx\596.wav', 'sounds/sfx'),
    ('sounds\sfx\597.wav', 'sounds/sfx'),
    ('sounds\sfx\598.wav', 'sounds/sfx'),
    ('sounds\sfx\599.wav', 'sounds/sfx'),
    ('sounds\sfx\600.wav', 'sounds/sfx'),
    ('sounds\sfx\601.wav', 'sounds/sfx'),
    ('sounds\sfx\602.wav', 'sounds/sfx'),
    ('sounds\sfx\603.wav', 'sounds/sfx'),
    ('sounds\sfx\604.wav', 'sounds/sfx'),
    ('sounds\sfx\605.wav', 'sounds/sfx'),
    ('sounds\sfx\606.wav', 'sounds/sfx'),
    ('sounds\sfx\607.wav', 'sounds/sfx'),
    ('sounds\sfx\608.wav', 'sounds/sfx'),
    ('sounds\sfx\609.wav', 'sounds/sfx'),
    ('sounds\sfx\610.wav', 'sounds/sfx'),
    ('sounds\sfx\611.wav', 'sounds/sfx'),
    ('sounds\sfx\612.wav', 'sounds/sfx'),
    ('sounds\sfx\613.wav', 'sounds/sfx'),
    ('sounds\sfx\614.wav', 'sounds/sfx'),
    ('sounds\sfx\615.wav', 'sounds/sfx'),
    ('sounds\sfx\616.wav', 'sounds/sfx'),
    ('sounds\sfx\617.wav', 'sounds/sfx'),
    ('sounds\sfx\618.wav', 'sounds/sfx'),
    ('sounds\sfx\619.wav', 'sounds/sfx'),
    ('sounds\sfx\620.wav', 'sounds/sfx'),
    ('sounds\sfx\621.wav', 'sounds/sfx'),
    ('sounds\sfx\622.wav', 'sounds/sfx'),
    ('sounds\sfx\623.wav', 'sounds/sfx'),
    ('sounds\sfx\624.wav', 'sounds/sfx'),
    ('sounds\sfx\625.wav', 'sounds/sfx'),
    ('sounds\sfx\626.wav', 'sounds/sfx'),
    ('sounds\sfx\627.wav', 'sounds/sfx'),
    ('sounds\sfx\628.wav', 'sounds/sfx'),
    ('sounds\sfx\629.wav', 'sounds/sfx'),
    ('sounds\sfx\630.wav', 'sounds/sfx'),
    ('sounds\sfx\631.wav', 'sounds/sfx'),
    ('sounds\sfx\632.wav', 'sounds/sfx'),
    ('sounds\sfx\633.wav', 'sounds/sfx'),
    ('sounds\sfx\634.wav', 'sounds/sfx'),
    ('sounds\sfx\635.wav', 'sounds/sfx'),
    ('sounds\sfx\636.wav', 'sounds/sfx'),
    ('sounds\sfx\637.wav', 'sounds/sfx'),
    ('sounds\sfx\638.wav', 'sounds/sfx'),
    ('sounds\sfx\639.wav', 'sounds/sfx'),
    ('sounds\sfx\640.wav', 'sounds/sfx'),
    ('sounds\sfx\641.wav', 'sounds/sfx'),
    ('sounds\sfx\642.wav', 'sounds/sfx'),
    ('sounds\sfx\643.wav', 'sounds/sfx'),
    ('sounds\sfx\644.wav', 'sounds/sfx'),
    ('sounds\sfx\645.wav', 'sounds/sfx'),
    ('sounds\sfx\646.wav', 'sounds/sfx'),
    ('sounds\sfx\647.wav', 'sounds/sfx'),
    ('sounds\sfx\648.wav', 'sounds/sfx'),
    ('sounds\sfx\649.wav', 'sounds/sfx'),
    ('sounds\sfx\650.wav', 'sounds/sfx'),
    ('sounds\sfx\651.wav', 'sounds/sfx'),
    ('sounds\sfx\652.wav', 'sounds/sfx'),
    ('sounds\sfx\653.wav', 'sounds/sfx'),
    ('sounds\sfx\654.wav', 'sounds/sfx'),
    ('sounds\sfx\655.wav', 'sounds/sfx'),
    ('sounds\sfx\656.wav', 'sounds/sfx'),
    ('sounds\sfx\657.wav', 'sounds/sfx'),
    ('sounds\sfx\658.wav', 'sounds/sfx'),
    ('sounds\sfx\659.wav', 'sounds/sfx'),
    ('sounds\sfx\660.wav', 'sounds/sfx'),
    ('sounds\sfx\661.wav', 'sounds/sfx'),
    ('sounds\sfx\662.wav', 'sounds/sfx'),
    ('sounds\sfx\663.wav', 'sounds/sfx'),
    ('sounds\sfx\664.wav', 'sounds/sfx'),
    ('sounds\sfx\665.wav', 'sounds/sfx'),
    ('sounds\sfx\666.wav', 'sounds/sfx'),
    ('sounds\sfx\667.wav', 'sounds/sfx'),
    ('sounds\sfx\668.wav', 'sounds/sfx'),
    ('sounds\sfx\669.wav', 'sounds/sfx'),
    ('sounds\sfx\670.wav', 'sounds/sfx'),
    ('sounds\sfx\671.wav', 'sounds/sfx'),
    ('sounds\sfx\672.wav', 'sounds/sfx'),
    ('sounds\sfx\673.wav', 'sounds/sfx'),
    ('sounds\sfx\674.wav', 'sounds/sfx'),
    ('sounds\sfx\675.wav', 'sounds/sfx'),
    ('sounds\sfx\676.wav', 'sounds/sfx'),
    ('sounds\sfx\677.wav', 'sounds/sfx'),
    ('sounds\sfx\678.wav', 'sounds/sfx'),
    ('sounds\sfx\679.wav', 'sounds/sfx'),
    ('sounds\sfx\680.wav', 'sounds/sfx'),
    ('sounds\sfx\681.wav', 'sounds/sfx'),
    ('sounds\sfx\682.wav', 'sounds/sfx'),
    ('sounds\sfx\683.wav', 'sounds/sfx'),
    ('sounds\sfx\684.wav', 'sounds/sfx'),
    ('sounds\sfx\685.wav', 'sounds/sfx'),
    ('sounds\sfx\686.wav', 'sounds/sfx'),
    ('sounds\sfx\687.wav', 'sounds/sfx'),
    ('sounds\sfx\688.wav', 'sounds/sfx'),
    ('sounds\sfx\689.wav', 'sounds/sfx'),
    ('sounds\sfx\690.wav', 'sounds/sfx'),
    ('sounds\sfx\691.wav', 'sounds/sfx'),
    ('sounds\sfx\692.wav', 'sounds/sfx'),
    ('sounds\sfx\693.wav', 'sounds/sfx'),
    ('sounds\sfx\694.wav', 'sounds/sfx'),
    ('sounds\sfx\695.wav', 'sounds/sfx'),
    ('sounds\sfx\696.wav', 'sounds/sfx'),
    ('sounds\sfx\697.wav', 'sounds/sfx'),
    ('sounds\sfx\698.wav', 'sounds/sfx'),
    ('sounds\sfx\699.wav', 'sounds/sfx'),
    ('sounds\sfx\700.wav', 'sounds/sfx'),
    ('sounds\sfx\701.wav', 'sounds/sfx'),
    ('sounds\sfx\702.wav', 'sounds/sfx'),
    ('sounds\sfx\703.wav', 'sounds/sfx'),
    ('sounds\sfx\704.wav', 'sounds/sfx'),
    ('sounds\sfx\705.wav', 'sounds/sfx'),
    ('sounds\sfx\706.wav', 'sounds/sfx'),
    ('sounds\sfx\707.wav', 'sounds/sfx'),
    ('sounds\sfx\708.wav', 'sounds/sfx'),
    ('sounds\sfx\709.wav', 'sounds/sfx'),
    ('sounds\sfx\710.wav', 'sounds/sfx'),
    ('sounds\sfx\711.wav', 'sounds/sfx'),
    ('sounds\sfx\712.wav', 'sounds/sfx'),
    ('sounds\sfx\713.wav', 'sounds/sfx'),
    ('sounds\sfx\714.wav', 'sounds/sfx'),
    ('sounds\sfx\715.wav', 'sounds/sfx'),
    ('sounds\sfx\716.wav', 'sounds/sfx'),
    ('sounds\sfx\717.wav', 'sounds/sfx'),
    ('sounds\sfx\718.wav', 'sounds/sfx'),
    ('sounds\sfx\719.wav', 'sounds/sfx'),
    ('sounds\sfx\720.wav', 'sounds/sfx'),
    ('sounds\sfx\721.wav', 'sounds/sfx'),
    ('sounds\sfx\722.wav', 'sounds/sfx'),
    ('sounds\sfx\723.wav', 'sounds/sfx'),
]

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=sound_files,
    hiddenimports=[
        'pygame',
        'numpy',
        'game.audio_system',
        'game.*',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Dawn_of_Stellar',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
