name: Issue Templates
description: 효율적인 이슈 관리를 위한 템플릿

templates:
  - name: 🐛 버그 리포트
    description: 게임에서 발생한 버그를 신고하세요
    title: "[BUG] "
    labels: ["bug", "needs-investigation"]
    body: |
      ## 🐛 버그 설명
      버그에 대한 명확하고 간결한 설명을 작성해주세요.

      ## 🔄 재현 단계
      버그를 재현하는 단계:
      1. '...'으로 이동
      2. '...'을 클릭
      3. '...'을 입력
      4. 오류 발생

      ## ✅ 예상 동작
      정상적으로 작동할 때 어떤 일이 일어나야 하는지 설명해주세요.

      ## ❌ 실제 동작
      실제로 어떤 일이 일어나는지 설명해주세요.

      ## 📸 스크린샷/로그
      해당하는 경우 스크린샷이나 오류 로그를 첨부해주세요.

      ## 🖥️ 환경 정보
      - 운영체제: [예: Windows 11]
      - Python 버전: [예: 3.11.5]
      - 게임 버전: [예: v3.1.1]
      - 추가 컨텍스트: [해당하는 경우]

      ## 📋 추가 컨텍스트
      버그에 대한 기타 컨텍스트나 정보를 추가해주세요.

  - name: ✨ 기능 요청
    description: 새로운 기능이나 개선사항을 제안하세요
    title: "[FEATURE] "
    labels: ["enhancement", "feature-request"]
    body: |
      ## 🚀 요청 기능
      어떤 기능을 원하시나요?

      ## 💡 동기/배경
      이 기능이 왜 필요한가요? 어떤 문제를 해결하나요?

      ## 📝 상세 설명
      원하는 솔루션에 대한 명확하고 간결한 설명을 작성해주세요.

      ## 🎯 사용자 스토리
      "~로서, 나는 ~을 원한다. 왜냐하면 ~이기 때문이다"

      ## 💭 대안 고려사항
      고려해봤던 다른 대안이나 해결책이 있나요?

      ## 📊 우선순위
      - [ ] 높음 (게임의 핵심 기능)
      - [ ] 보통 (좋으면 있으면 좋은 기능)
      - [ ] 낮음 (나중에 구현해도 되는 기능)

      ## 🔗 관련 이슈/PR
      관련된 이슈나 풀 리퀘스트가 있다면 연결해주세요.

  - name: 📚 문서 개선
    description: 문서의 오류나 개선점을 제안하세요
    title: "[DOCS] "
    labels: ["documentation", "good first issue"]
    body: |
      ## 📄 문서 위치
      어떤 문서에 관한 것인가요? (파일명이나 링크)

      ## 🔍 발견된 문제
      문서에서 발견한 문제나 개선점을 설명해주세요.

      ## ✅ 제안하는 개선사항
      어떻게 개선되어야 한다고 생각하시나요?

      ## 🎯 대상 독자
      - [ ] 신규 플레이어
      - [ ] 숙련된 플레이어
      - [ ] 개발자
      - [ ] 기여자

      ## 📋 추가 정보
      기타 관련 정보나 제안사항이 있다면 작성해주세요.

  - name: 🎮 게임플레이 피드백
    description: 게임 밸런스나 플레이 경험에 대한 피드백
    title: "[GAMEPLAY] "
    labels: ["gameplay", "feedback"]
    body: |
      ## 🎯 피드백 분야
      - [ ] 전투 시스템
      - [ ] 직업 밸런스
      - [ ] 던전 디자인
      - [ ] UI/UX
      - [ ] 스토리
      - [ ] 기타: ___

      ## 📊 현재 상황
      현재 게임의 어떤 부분에 대한 피드백인가요?

      ## 💭 플레이어 경험
      해당 기능을 사용하면서 어떤 느낌이었나요?

      ## 🔄 제안하는 변경사항
      어떻게 개선되면 좋을지 구체적으로 제안해주세요.

      ## 📈 플레이 정보
      - 플레이 시간: [예: 10시간]
      - 달성한 층수: [예: 50층]
      - 주로 사용하는 직업: [예: 전사, 아크메이지]
      - 난이도: [예: 보통]

      ## 🎮 추가 의견
      게임에 대한 기타 의견이나 제안사항이 있나요?

  - name: 🚀 성능 문제
    description: 게임 성능 관련 문제를 신고하세요
    title: "[PERFORMANCE] "
    labels: ["performance", "needs-investigation"]
    body: |
      ## ⚡ 성능 문제 설명
      어떤 성능 문제를 경험하고 계신가요?

      ## 📊 증상
      - [ ] 게임이 느려짐
      - [ ] 높은 CPU 사용량
      - [ ] 높은 메모리 사용량
      - [ ] 응답 없음/정지
      - [ ] 기타: ___

      ## 🔍 발생 상황
      언제 이 문제가 발생하나요?
      - [ ] 게임 시작 시
      - [ ] 전투 중
      - [ ] 던전 탐험 중
      - [ ] 메뉴 사용 시
      - [ ] 장시간 플레이 후
      - [ ] 항상

      ## 🖥️ 시스템 사양
      - CPU: [예: Intel i5-8400]
      - RAM: [예: 16GB]
      - 저장장치: [예: SSD/HDD]
      - 운영체제: [예: Windows 11]
      - Python 버전: [예: 3.11.5]

      ## 📈 성능 데이터
      가능하다면 작업 관리자나 성능 모니터링 도구의 스크린샷을 첨부해주세요.

      ## 🔧 시도한 해결책
      이미 시도해본 해결 방법이 있나요?

  - name: ❓ 질문/도움말
    description: 게임 사용법이나 기능에 대해 질문하세요
    title: "[QUESTION] "
    labels: ["question", "help wanted"]
    body: |
      ## ❓ 질문 내용
      무엇이 궁금하신가요?

      ## 🎯 목표
      무엇을 달성하려고 하시나요?

      ## 🔍 시도한 방법
      이미 시도해본 방법이 있나요?

      ## 📚 참고한 문서
      어떤 문서나 가이드를 참고하셨나요?

      ## 🖥️ 환경 정보
      - 운영체제: [예: Windows 11]
      - 게임 버전: [예: v3.1.1]
      - 플레이 모드: [예: 일반, AI 모드]

      ## 📋 추가 컨텍스트
      질문과 관련된 추가 정보가 있다면 작성해주세요.
