name: Build Release
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run basic tests
      run: |
        python -m pytest test_basic.py --verbose
    - name: Test game modules import
      run: |
        python -c "
        import sys
        import os
        sys.path.insert(0, '.')
        try:
            import version
            print(f'✅ Version: {version.VERSION}')
            print('✅ 기본 테스트 통과')
        except Exception as e:
            print(f'❌ 테스트 실패: {e}')
            sys.exit(1)
        "
